# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gatsbyx/curvesLibrary

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gatsbyx/curvesLibrary

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gatsbyx/curvesLibrary/CMakeFiles /home/gatsbyx/curvesLibrary//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gatsbyx/curvesLibrary/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named curvesLibrary

# Build rule for target.
curvesLibrary: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 curvesLibrary
.PHONY : curvesLibrary

# fast build rule for target.
curvesLibrary/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/build
.PHONY : curvesLibrary/fast

src/circle.o: src/circle.cpp.o
.PHONY : src/circle.o

# target to build an object file
src/circle.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/circle.cpp.o
.PHONY : src/circle.cpp.o

src/circle.i: src/circle.cpp.i
.PHONY : src/circle.i

# target to preprocess a source file
src/circle.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/circle.cpp.i
.PHONY : src/circle.cpp.i

src/circle.s: src/circle.cpp.s
.PHONY : src/circle.s

# target to generate assembly for a file
src/circle.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/circle.cpp.s
.PHONY : src/circle.cpp.s

src/curve.o: src/curve.cpp.o
.PHONY : src/curve.o

# target to build an object file
src/curve.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/curve.cpp.o
.PHONY : src/curve.cpp.o

src/curve.i: src/curve.cpp.i
.PHONY : src/curve.i

# target to preprocess a source file
src/curve.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/curve.cpp.i
.PHONY : src/curve.cpp.i

src/curve.s: src/curve.cpp.s
.PHONY : src/curve.s

# target to generate assembly for a file
src/curve.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/curve.cpp.s
.PHONY : src/curve.cpp.s

src/curve3abstract.o: src/curve3abstract.cpp.o
.PHONY : src/curve3abstract.o

# target to build an object file
src/curve3abstract.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/curve3abstract.cpp.o
.PHONY : src/curve3abstract.cpp.o

src/curve3abstract.i: src/curve3abstract.cpp.i
.PHONY : src/curve3abstract.i

# target to preprocess a source file
src/curve3abstract.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/curve3abstract.cpp.i
.PHONY : src/curve3abstract.cpp.i

src/curve3abstract.s: src/curve3abstract.cpp.s
.PHONY : src/curve3abstract.s

# target to generate assembly for a file
src/curve3abstract.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/curve3abstract.cpp.s
.PHONY : src/curve3abstract.cpp.s

src/curves3factory.o: src/curves3factory.cpp.o
.PHONY : src/curves3factory.o

# target to build an object file
src/curves3factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/curves3factory.cpp.o
.PHONY : src/curves3factory.cpp.o

src/curves3factory.i: src/curves3factory.cpp.i
.PHONY : src/curves3factory.i

# target to preprocess a source file
src/curves3factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/curves3factory.cpp.i
.PHONY : src/curves3factory.cpp.i

src/curves3factory.s: src/curves3factory.cpp.s
.PHONY : src/curves3factory.s

# target to generate assembly for a file
src/curves3factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/curves3factory.cpp.s
.PHONY : src/curves3factory.cpp.s

src/ellipse.o: src/ellipse.cpp.o
.PHONY : src/ellipse.o

# target to build an object file
src/ellipse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/ellipse.cpp.o
.PHONY : src/ellipse.cpp.o

src/ellipse.i: src/ellipse.cpp.i
.PHONY : src/ellipse.i

# target to preprocess a source file
src/ellipse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/ellipse.cpp.i
.PHONY : src/ellipse.cpp.i

src/ellipse.s: src/ellipse.cpp.s
.PHONY : src/ellipse.s

# target to generate assembly for a file
src/ellipse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/ellipse.cpp.s
.PHONY : src/ellipse.cpp.s

src/helix3.o: src/helix3.cpp.o
.PHONY : src/helix3.o

# target to build an object file
src/helix3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/helix3.cpp.o
.PHONY : src/helix3.cpp.o

src/helix3.i: src/helix3.cpp.i
.PHONY : src/helix3.i

# target to preprocess a source file
src/helix3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/helix3.cpp.i
.PHONY : src/helix3.cpp.i

src/helix3.s: src/helix3.cpp.s
.PHONY : src/helix3.s

# target to generate assembly for a file
src/helix3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/curvesLibrary.dir/build.make CMakeFiles/curvesLibrary.dir/src/helix3.cpp.s
.PHONY : src/helix3.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... curvesLibrary"
	@echo "... src/circle.o"
	@echo "... src/circle.i"
	@echo "... src/circle.s"
	@echo "... src/curve.o"
	@echo "... src/curve.i"
	@echo "... src/curve.s"
	@echo "... src/curve3abstract.o"
	@echo "... src/curve3abstract.i"
	@echo "... src/curve3abstract.s"
	@echo "... src/curves3factory.o"
	@echo "... src/curves3factory.i"
	@echo "... src/curves3factory.s"
	@echo "... src/ellipse.o"
	@echo "... src/ellipse.i"
	@echo "... src/ellipse.s"
	@echo "... src/helix3.o"
	@echo "... src/helix3.i"
	@echo "... src/helix3.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

